### PR TITLE
Frontend Hooks Part 1: App module

### PR DESCRIPTION
**Pull request by detri**
# Context
The front end needs converted to functional components, so we can either use useReducer or ditch redux concepts altogether for the context API and hooks. This PR will convert the front end as it is from class components to functional components which use hooks.

This is part 1 which converts the "app" module to FCs using hooks.

# Validation
Make sure everything works as it did before. Test logins, game page, etc.

# Additional notes
This PR also adds tests.

This uses react-redux hooks to maintain compatibility with the Provider while we sort out converting the rest of the app and getting rid of react-redux in favor of either the useContext API or useContext + useReducer combo.

### CODE REVIEW

**Comment by danielgrijalva** [comment]
Hey, I just finished reviewing your changes… wow, fantastic work! I’m gonna run everything locally just to see it for myself 😅

Are you planning on adding more commits to this PR? Just asking before I merge.

**Comment by detri** [comment]
Go ahead and merge when ready - next will be the games module!

**Comment by danielgrijalva** [comment]
The logout functionality is not working for me… it’s still using the Redux actions for that 🤔 (navbar component around line 94)

**Comment by danielgrijalva** [comment]
Alright I fixed it! changed it from

```jsx
() => logout(dispatch, getState)
```

to

```jsx
() => dispatch(logout())
```

I’m gonna push it to your fork and then merge.

**Comment by detri** [comment]
Sounds good! Thanks for the fix, it's been a while since I used thunks so I wasn't sure if it would work or not.

**Pull request merged**
