### PR TITLE
Wrong developer in game title

### PR DESCRIPTION
**Pull request by raufabr**
Changed rendering logic to show first publisher instead of first developer

### CODE REVIEW

**Comment by danielgrijalva** [comment]
Hi @raufabr thanks for giving it a go! but I guess I wasn't clear enough... the problem is that I want to show the **developer** name, not the publisher. And some games (like Rocket League or Firewatch) are not showing the developer name...

**Comment by raufabr** [comment]
@danielgrijalva sorry I've been busy last week.
I'll finish it tonight or tomorrow and submit the pull request.

What would you like to be shown if the developer is empty?
Do you want an icon or something when the dev and publisher are the same company?

**Comment by raufabr** [comment]
Should be completed now. Returning the first developer only.

**Comment by danielgrijalva** [comment]
@raufabr if there's no developer well, the developer field should not be displayed. The same for the publisher! And I don't think it's necessary to do anything when the dev and publisher are the same :)

**Comment by raufabr** [comment]
@danielgrijalva are we ok to close this task?

**Pull request closed without merging**
