### PR TITLE
Initial Frontend Tests (#19) 

### PR DESCRIPTION
**Pull request by mikesmith**
Configured the project for Jest + Enzyme. Added a couple of initial tests for the Popular and Features components. There are a lot more tests to write but I wanted to get a WIP PR out to get some early feedback.

I added snapshot testing using ```enzyme-to-json```. Please let me know if there are any strong feelings for having/not having snapshot testing. I think it is a great compliment to normal assertion testing and very easy to implement but I can remove it if we feel this is too much or it will crowd the folders with ```__snapshot__``` folders.

### CODE REVIEW

**Comment by danielgrijalva** [comment]
The tests look great so far, very solid, thanks! How can I run them? `npm run test`?

Regarding snapshots... I agree that they can be very useful, but seeing that Overworld is in early development and **constantly changing**, I think they might slow us down because right now, the reference snapshots would have to be updated basically with every new PR. But we can implement them once we have a solidified UI with all/most of the planned features! :smile:

**Comment by mikesmith** [comment]
Thanks @danielgrijalva for the feedback.

To run the tests: ```npm test```

You are right, it would probably be best to hold off for now. I will remove the current snapshots and the tests. I will leave the ability to do snapshots so when it makes more sense, we can just start writing the tests. Thanks!

**Comment by mikesmith** [comment]
I've updated the PR to remove the snapshot testing files and tests. I've also updated the popular component unit tests to have a lot more coverage. Please send over any feedback or let me know anything that should be changed.

I'm interested in continuing to add coverage for the frontend; however, I wonder when should we merge this PR so the framework is in master to allow others to add tests if they would like?

Also, I can update the test documentation. Should that be a new issue?

Thanks!

**Comment by danielgrijalva** [comment]
Seems to me that this is ready for master, we can add more tests with new PRs. If you're comfortable with that, I can merge it right now! :+1: 

Feel free to submit a new issue for the testing documentation... once you start with that, open [this link](https://app.gitbook.com/invite/overworld?invite=-Lk4wXNK1s2ux5k3iL84), it's an invitation for GitBook - should make it easier for you to add docs! :smiley:

Also, I'm looking to update the Travis CI configuration so it supports both backend and frontend. I've put up the following .travis.yml file using [this](https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages) and [this](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/):
```yml
dist: xenial
matrix:
  include:
    - language: python
    python:
      - "3.7"
    install:
      - pip install -r backend/requirements.txt
      - pip install psycopg2 --quiet
      - pip install codecov
    services:
      - postgresql
    before_script:
      - psql -c "CREATE DATABASE overworld;" -U postgres
    script:
      - python backend/manage.py migrate
      - coverage run backend/manage.py test games actions users
    after_success:
      - codecov
  include:
    - language: node_js
    node_js: 
      - "8.10"
    before_script:
      - cd frontend/
      - npm ci
    script:
      - npm test
```
The Python stuff stays the same - just added the node_js config and `matrix` for supporting multiple languages. The thing is, I'm not really sure if it will work, are you familiar with a setup like this? Also, I haven't done much digging about code coverage reports with codecov for both languages... we'll see.

**Comment by mikesmith** [comment]
Awesome! Thanks. I'm comfortable merging this to master when you are ready.

I'll go ahead and open up a new issue for the documentation and follow the given link.

Regarding the Travis CI and code coverage. I am not really familiar with setting these up. I did take a look at the links you provided and it seems like you have it setup correctly. For codecov, I found some resources that might help: [node codecov example](https://github.com/codecov/example-node), [jest example](https://github.com/codecov/example-node#jest), [merging results](https://docs.codecov.io/docs/merging-reports) and [npm codecov package](https://www.npmjs.com/package/codecov).

**Comment by mikesmith** [comment]
@danielgrijalva 
After looking through some of the resources, I took what you had and added some of the `codecov` stuff.  I added `npm install -g codecov` in the before script section and the `codecov` call after the tests have run. Here are some examples: [Example](https://github.com/codecov/example-node)

``` yaml
dist: xenial
matrix:
  include:
    - language: python
    python:
      - "3.7"
    install:
      - pip install -r backend/requirements.txt
      - pip install psycopg2 --quiet
      - pip install codecov
    services:
      - postgresql
    before_script:
      - psql -c "CREATE DATABASE overworld;" -U postgres
    script:
      - python backend/manage.py migrate
      - coverage run backend/manage.py test games actions users
    after_success:
      - codecov
  include:
    - language: node_js
    node_js: 
      - "8.10"
    before_script:
      - cd frontend/
      - npm ci
      - npm install -g codecov
    script:
      - npm test
      - codecov
```

I think we would need to add the following configuration to the package.json for codecov to work with jest. Used [this](https://github.com/codecov/example-node#jest) as a resource.

``` json
"jest": {
  "coverageDirectory": "./coverage/",
  "collectCoverage": true
}
```

Let me know what you think. Hopefully this helps. Thanks!

**Comment by mikesmith** [comment]
So... I tried out some of the code coverage stuff locally. It looks like updating the jest configuration will not work with an app that was created with `create-react-app`. However, I think I figured out what may be able to work without updating the jest configs. Here is a reference to an [issue](https://github.com/facebook/create-react-app/issues/2825) that pointed me in the right direction.

```yaml
dist: xenial
matrix:
  include:
    - language: python
    python:
      - "3.7"
    install:
      - pip install -r backend/requirements.txt
      - pip install psycopg2 --quiet
      - pip install codecov
    services:
      - postgresql
    before_script:
      - psql -c "CREATE DATABASE overworld;" -U postgres
    script:
      - python backend/manage.py migrate
      - coverage run backend/manage.py test games actions users
    after_success:
      - codecov
  include:
    - language: node_js
    node_js: 
      - "8.10"
    before_script:
      - cd frontend/
      - npm ci
      - npm install -g codecov
    script:
      - npm test -- --coverage && codecov
```

I'm still not sure how to merge the two code coverage reports; however, I think this will get the frontend tests running with code coverage. Thanks!

**Comment by danielgrijalva** [comment]
@mikesmith thanks for the help, just gave it a try locally and it successfully generates a coverage report!
image

I'm gonna publish this changes to master along with the new codecov/travis setup, it should work...

**Pull request merged**
