### PR TITLE
added status check for action

### PR DESCRIPTION
**Pull request by bovas85**
Action was not checking for status 404 (this can be extended to other statuses in a map if needed)

### CODE REVIEW

**Comment by bovas85** [comment]
please review :)

**Comment by danielgrijalva** [comment]
Hi @bovas85, sorry for the absence and thanks for your PR! what exactly is this fix for? would you mind explaining the details of _what_ you're trying to accomplish/fix?

**Comment by bovas85** [comment]
Hey @danielgrijalva this is related to the issue https://github.com/danielgrijalva/overworld/issues/104

**Comment by danielgrijalva** [comment]
@bovas85 I see! awesome that you got that fixed. Merging now...

**Pull request merged**
