### PR TITLE
Add script to setup and run backend

### PR DESCRIPTION
**Pull request by bingocaller**
Hello there! I was trying to get the project up and running on macOS but
I ran into some issues, so I thought I would build a little script to
help myself and others.

Right now it's built with macOS and Homebrew in mind, but it could
potentially be built out to support other OSes and package managers.

---

The script tries to determine if pg_config is available and offers to
install it via Homebrew.
Script then tries to determine which version of Python is the default.
If default is Python 2 and Python 3 is available, the script will try to
run commands using Python 3. If Python 3 isn't available it will offer
to install it, again via Homebrew.

### CODE REVIEW

**Comment by danielgrijalva** [comment]
Hey @bingocaller sorry for the absence. This is great, thanks! would you mind adding a bit of documentation so that everyone knows about this script?

**Comment by bingocaller** [comment]
@danielgrijalva Sure thing! Let me know when I have access and I can get started! 🙂

**Comment by danielgrijalva** [comment]
@bingocaller just follow [this link](https://app.gitbook.com/invite/overworld?invite=-LhMmS86OvislX6iL0D3) to join the organization. Please write on the Getting Started > Setup section (maybe below a "Troubleshooting" heading?) 😄

**Comment by bingocaller** [comment]
@danielgrijalva Okay, I added a draft in GitBook. Let me know what you think!

**Comment by danielgrijalva** [comment]
@bingocaller looks great! I'll merge this now. Thanks! ✨

**Pull request merged**
